spring:
  application:
    name: ms-offers-basic
  server:
    port: 3000
	
offers:
  discount:	40%
  
management:
  endpoints:
    web:
      exposure:
        include: *

database:
  enabled: true
  dbclarodesarrollo:
    jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
    name: test